// Generated by scripts/generate-recipe-catalog-index.mjs. Do not edit.
import recipe0 from "./recipes/amandin.json";
import recipe1 from "./recipes/banana-bread-du-kona-inn.json";
import recipe2 from "./recipes/brownies.json";
import recipe3 from "./recipes/cake-au-chevre-et-courgettes.json";
import recipe4 from "./recipes/cake-aux-tomates-sechees-et-a-la-feta.json";
import recipe5 from "./recipes/cake-chevre-noix-olives.json";
import recipe6 from "./recipes/cake-d-ete-tout-vert.json";
import recipe7 from "./recipes/cake-moelleux-au-citron-de-pierre-herme.json";
import recipe8 from "./recipes/cake-orange.json";
import recipe9 from "./recipes/clafoutis-aux-abricots.json";
import recipe10 from "./recipes/clafoutis-poires-et-framboises.json";
import recipe11 from "./recipes/cocotte-de-cabillaud-aux-courgettes-et-curry.json";
import recipe12 from "./recipes/cookies-aux-pepites-de-chocolat-et-fleur-de-sel.json";
import recipe13 from "./recipes/coulants-au-chocolat.json";
import recipe14 from "./recipes/crumble-aux-pommes-du-verger.json";
import recipe15 from "./recipes/flan-au-lait-concentre-sucre-nestle.json";
import recipe16 from "./recipes/gateau-au-chocolat.json";
import recipe17 from "./recipes/gateau-au-citron.json";
import recipe18 from "./recipes/gateau-aux-pommes.json";
import recipe19 from "./recipes/gougeres.json";
import recipe20 from "./recipes/lasagnes-vegetariennes.json";
import recipe21 from "./recipes/lasagnes.json";
import recipe22 from "./recipes/macaron-tante-maria.json";
import recipe23 from "./recipes/mayonnaise.json";
import recipe24 from "./recipes/osso-buco.json";
import recipe25 from "./recipes/pain-de-poisson.json";
import recipe26 from "./recipes/papillotes-de-cabillaud.json";
import recipe27 from "./recipes/pate-feuilletee-maman.json";
import recipe28 from "./recipes/pate-sucree-de-pierre-herme.json";
import recipe29 from "./recipes/pates-carbonara.json";
import recipe30 from "./recipes/salade-de-lentilles.json";
import recipe31 from "./recipes/sauce-bolognaise.json";
import recipe32 from "./recipes/smoothie-banane-et-fruits-rouges.json";
import recipe33 from "./recipes/soupe-de-champagne.json";
import recipe34 from "./recipes/tarte-aux-amandes-et-confiture-de-framboises.json";
import recipe35 from "./recipes/tiramisu.json";
import recipe36 from "./recipes/vacherin.json";
import recipe37 from "./recipes/veloute-de-courgettes.json";

export const rawRecipeCatalog = [
  { sourcePath: "./recipes/amandin.json", recipe: recipe0 },
  { sourcePath: "./recipes/banana-bread-du-kona-inn.json", recipe: recipe1 },
  { sourcePath: "./recipes/brownies.json", recipe: recipe2 },
  { sourcePath: "./recipes/cake-au-chevre-et-courgettes.json", recipe: recipe3 },
  { sourcePath: "./recipes/cake-aux-tomates-sechees-et-a-la-feta.json", recipe: recipe4 },
  { sourcePath: "./recipes/cake-chevre-noix-olives.json", recipe: recipe5 },
  { sourcePath: "./recipes/cake-d-ete-tout-vert.json", recipe: recipe6 },
  { sourcePath: "./recipes/cake-moelleux-au-citron-de-pierre-herme.json", recipe: recipe7 },
  { sourcePath: "./recipes/cake-orange.json", recipe: recipe8 },
  { sourcePath: "./recipes/clafoutis-aux-abricots.json", recipe: recipe9 },
  { sourcePath: "./recipes/clafoutis-poires-et-framboises.json", recipe: recipe10 },
  { sourcePath: "./recipes/cocotte-de-cabillaud-aux-courgettes-et-curry.json", recipe: recipe11 },
  { sourcePath: "./recipes/cookies-aux-pepites-de-chocolat-et-fleur-de-sel.json", recipe: recipe12 },
  { sourcePath: "./recipes/coulants-au-chocolat.json", recipe: recipe13 },
  { sourcePath: "./recipes/crumble-aux-pommes-du-verger.json", recipe: recipe14 },
  { sourcePath: "./recipes/flan-au-lait-concentre-sucre-nestle.json", recipe: recipe15 },
  { sourcePath: "./recipes/gateau-au-chocolat.json", recipe: recipe16 },
  { sourcePath: "./recipes/gateau-au-citron.json", recipe: recipe17 },
  { sourcePath: "./recipes/gateau-aux-pommes.json", recipe: recipe18 },
  { sourcePath: "./recipes/gougeres.json", recipe: recipe19 },
  { sourcePath: "./recipes/lasagnes-vegetariennes.json", recipe: recipe20 },
  { sourcePath: "./recipes/lasagnes.json", recipe: recipe21 },
  { sourcePath: "./recipes/macaron-tante-maria.json", recipe: recipe22 },
  { sourcePath: "./recipes/mayonnaise.json", recipe: recipe23 },
  { sourcePath: "./recipes/osso-buco.json", recipe: recipe24 },
  { sourcePath: "./recipes/pain-de-poisson.json", recipe: recipe25 },
  { sourcePath: "./recipes/papillotes-de-cabillaud.json", recipe: recipe26 },
  { sourcePath: "./recipes/pate-feuilletee-maman.json", recipe: recipe27 },
  { sourcePath: "./recipes/pate-sucree-de-pierre-herme.json", recipe: recipe28 },
  { sourcePath: "./recipes/pates-carbonara.json", recipe: recipe29 },
  { sourcePath: "./recipes/salade-de-lentilles.json", recipe: recipe30 },
  { sourcePath: "./recipes/sauce-bolognaise.json", recipe: recipe31 },
  { sourcePath: "./recipes/smoothie-banane-et-fruits-rouges.json", recipe: recipe32 },
  { sourcePath: "./recipes/soupe-de-champagne.json", recipe: recipe33 },
  { sourcePath: "./recipes/tarte-aux-amandes-et-confiture-de-framboises.json", recipe: recipe34 },
  { sourcePath: "./recipes/tiramisu.json", recipe: recipe35 },
  { sourcePath: "./recipes/vacherin.json", recipe: recipe36 },
  { sourcePath: "./recipes/veloute-de-courgettes.json", recipe: recipe37 },
] as const;
